// agents/14-notes/index.js
// On-demand: turn a YouTube video or article URL into structured notes.
// Usage (local):   node agents/14-notes/index.js "https://youtu.be/..."
// Usage (Actions): run the "Video/Article Notes" workflow and paste a URL (14-notes.yml).
import { writeFileSync } from "node:fs";
import { generateNotes } from "./generate.js";

const url = process.argv[2] || process.env.NOTE_URL;
if (!url) { console.error("Pass a URL (arg) or set NOTE_URL."); process.exit(1); }

const notes = await generateNotes(url);

// Email the notes if Resend is configured (works in GitHub Actions).
if (process.env.RESEND_API_KEY) {
  const { notifyEmail } = await import("../../lib/notify.js");
  const { renderEmail } = await import("../../lib/email-template.js");
  const body = notes.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\n/g, "<br>");
  const safeUrl = url.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
  const html = renderEmail({
    title: "📝 Structured Notes",
    kicker: "ON-DEMAND",
    accent: "#185FA5",
    blocks: [{ type: "text", html: `<b>${safeUrl}</b><br><br>${body}` }],
    footer: "Generated by your notes agent",
  });
  await notifyEmail(`📝 Notes: ${url}`, html);
}
// Also save a local file when run on your machine.
try {
  const file = `notes-${Date.now()}.md`;
  writeFileSync(file, `# Notes: ${url}\n\n${notes}\n`);
  console.log(`Saved ${file}`);
} catch {}
console.log(`\n${notes}`);
